project:
  type: book
  output-dir: _output/pdf
  render:
    - "*.qmd"
    - "!ignored.qmd"
    - "!code/"
    - "!data/"
    - "!images/"

book:
  title: "Graph Time"
  chapters:
    - index.qmd
    - 01-introduction.qmd
    - 02-data-engineering.qmd
    - 03-graph-data-model.qmd
    - 04-timetable-metrics.qmd
    - 05-future-opportunities.qmd
    - 06-conclusion.qmd
    - references.qmd

format:
  pdf: 
    documentclass: scrreprt

execute:
  freeze: auto
