---
title: "Code Gists"
---

Complete code can be found in these Github gists.


[**Graph Timetable - Quarto - Config and Misc**](https://gist.github.com/zoonalink/818cae9f20db1f1417725a1f297ff061)

1. config.py
2. logger_config.py
3. neo4j_schema.py
4. utils.py
5. connect_to_neo4j.py
6. connect_to_rdb.py


<script src="https://gist.github.com/zoonalink/818cae9f20db1f1417725a1f297ff061.js"></script><div class="gist-preview"></div> 


[**Graph Timetable - Quarto - SQL Queries**](https://gist.github.com/zoonalink/4ba9fa5bf75ac21c1537d8176ee5c700)

1. create_temp_tables.sql
2. node-activity-by-pos-temp.sql
3. node-activityType-by-pos-temp.sql
4. node-dept-all.sql
5. node-module-by-pos-temp.sql
6. node-pos-by-pos-temp.sql
7. node-room-by-pos-temp.sql
8. node-staff-by-pos-temp.sql
9. node-student-by-pos-temp.sql
10. rel-activity-module-by-pos-temp.sql
11. rel-activity-room-by-pos-temp.sql
12. rel-module-programme-by-pos-temp.sql
13. rel-staff-activity-by-pos-temp.sql
14. rel-student-activity-by-pos-temp.sql

<script src="https://gist.github.com/zoonalink/4ba9fa5bf75ac21c1537d8176ee5c700.js"></script>
<div class="gist-preview"></div> 



[**Graph Timetable - Quarto - Extract**](https://gist.github.com/zoonalink/d3bafb3100a162c50694be699bfc8e3f)

1. temp_table_loader
2. extract_sql_file
3. extract_data
4. extract_main

<script src="https://gist.github.com/zoonalink/d3bafb3100a162c50694be699bfc8e3f.js"></script>



[**Graph Timetable - Quarto - Upload to Google Drive**](https://gist.github.com/zoonalink/450bff1a92d2efcde58ab4b9edc3e7ae)

1. gdrive_upload
2. google_drive_utils

<script src="https://gist.github.com/zoonalink/450bff1a92d2efcde58ab4b9edc3e7ae.js"></script>




[**Graph Timetable - Quarto - Load**](https://gist.github.com/zoonalink/ce5e1f3e578a5eeed05144f3676af409)

1. load_schema
2. load_utils
3. load_nodes
4. load_relationships
5. convert_properties
6. set_display_properties
7. load_main

<script src="https://gist.github.com/zoonalink/ce5e1f3e578a5eeed05144f3676af409.js"></script>



[**Graph Timetable - Quarto - Process**](https://gist.github.com/zoonalink/125673550192ff7515628b7d00879114)

1. process_utils
2. process_node
3. process_main

<script src="https://gist.github.com/zoonalink/125673550192ff7515628b7d00879114.js"></script>


