---
title: "Exploring Graph Data Models for Timetabling Insights"
subtitle: "A proof-of-concept data engineering project"
author: "Petter Lovehagen"
date: "29 August 2024"
---

**Supervisor**: [Xiaodong Li](https://people.uwe.ac.uk/Person/XiaodongLi)

**Programme**: [MSc Data Science](https://courses.uwe.ac.uk/INB112/data-science)

**Abstract**: 

Timetables are central to the daily experience of university students and staff.  Timetables also influence resource utilisation and play a key role in institutional efficiency.  In short, timetables are critical to the individual experience and the overall success of an institution.  But timetables are also contentious - there is no 'perfect' timetable, only a series of compromises that balance competing priorities. 

This project explores the use of graph data models to provide deeper insights into timetables.  The aim is to investigate the viability of graph-based approaches for enhanced timetabling analytics and reporting.  The objectives include designing a graph data model, developing a configurable ETL pipeline, and discussing how graph-based analysis could contribute to quantitaviely measuring timetable quality by introducing the concept of a *Timetable Quality Index*.  

The project is a proof-of-concept, and the results are intended to inform future research and development in the area of timetabling analytics.  The project is implemented primarily in Python, using the Neo4j cloud instance graph database, and the results and documentation are presented in a Quarto website.


**Word Count**:

- Abstract: 
- Main:
- Appendices:
- 




<iframe width="560" height="315" src="https://drive.google.com/file/d/1rl6TkRq3W9RpBLToaYLPGUDe6xsfFsM1/preview" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>



