---
title: "Introduction" 
---

University timetabling is the complex process of scheduling curriculum elements (modules, programmes), rooms, and resources within an academic institution. At its simplest, it involves collecting and combining time slots, rooms, students and other resources while satisfying a multitude of constraints and preferences to achieve a *viable* outcome.




## What is University Timetabling? 

But it is never as simple as that...

University timetabling is a critical administrative task that involves creating a learning and teaching schedule for students and staff, respectively.  It is undertaken by *schedulers* who are multi-skilled professionals needing to incorporate various skills including data analysis, change management, negotiating, complaint management and optimisation.  (Dowland, 2018)

Timetabling complexity can vary from *simple* room bookings on one end of the scale to bespoke, individual schedules.  Institutional goals can range from maximising room utilisation to delivering a great student experience.  More often than not, university will attempt to deliver **everything** and only realise a fraction of the objectives.  There are several reasons for this and they will vary with each institution, but fundamentally, certain objectives are contradictory - if you maximise room utilisation, experience is likely to worsen.  The other major reason is that there is no such thing as a *universally* good timetable - what is good for one student will almost certainly not be good for another.  

So timetabling and timetablers always find themselves in the firing line of criticism - they cannot win and the old adage 'no news is good news' could not be truer. 

## Why is University Timetabling Challenging?

The complexity of university timetabling stems from several factors:

**Scale**: Universities often have tens of thousands of students, hundreds of programmes (courses), thousands of modules, and limited resources.
**Constraints**: There are numerous hard constraints (e.g., room capacity) and soft constraints (e.g., preferences) to consider.
**Interdependencies**: Changes in one part of the schedule have cascading effects on other parts.
**Diversity of Needs**: Different organisational units (colleges, faculties, schools, departments) have varying requirements and preferences.
**Optimisation Goals**: Balancing efficiency, fairness, and quality of education.

## Operational Challenges

Some of the main operational challenges in university timetabling include:

* **Resource Utilisation**: Maximising the use of available rooms and equipment.
* **Conflict Resolution**: Avoiding scheduling conflicts for students and staff.
* **Adaptability**: Accommodating last-minute changes or unforeseen circumstances.
* **Equity**: Ensuring fair distribution of desirable time slots and resources.
* **Data Quality and Interoperability**: Ensuring clean, accurate data flows between interconnected systems.
* **Curriculum Complexity**: Managing the intricacies of programme deliveries including excluded combinations, elective choices.
* **Balancing Flexibility and Structure**: Accommodating diverse teaching styles while maintaining a consistent schedule.
* **Stakeholder Communication**: Effectively conveying timetable information and changes to all parties involved.




NOTES:

## Motivation

My motivation for this project stems from recognising the limitations of current timetabling approaches. Traditional methods, while valuable, often struggle to capture the nuances and complexities of the modern university environment. The current focus in timetabling is predominantly on data collection (gathering requirements and data elements) and timetable generation (primarily focused on avoiding hard constraint violations such as clashes). However, the post-timetable evaluation and analysis phases are not as well developed. This gap exists for two main reasons: firstly, such analysis is inherently difficult to perform, and secondly, there's often a lack of clarity about what exactly to look for in a "good" timetable beyond the absence of constraint violations.

I believe that graph data structures could be particularly useful for gaining insights and facilitating data exploration in the post-timetable generation phase. The increasing emphasis on student-centered learning and the need to provide a positive student experience have highlighted the shortcomings of conventional timetabling methods, especially in terms of quality assessment and improvement.

Anecdotal evidence suggests that the relational database structures commonly employed in timetabling systems may hinder our ability to effectively measure and report on the "quality" of a timetable. This limitation can impede efforts to understand the impact of timetables on student experiences and to make data-driven improvements.

Given the highly relational nature of timetables, where curriculum, lecturers, rooms, and time slots are interconnected in intricate ways, I hypothesise that a graph-based approach *could* offer a more natural and insightful way to represent and analyse timetable data. Graph databases, designed to handle complex relationships and interconnected data, have the potential to unlock new avenues for understanding and optimizing university timetables, particularly in the post-generation analysis phase where traditional methods fall short.









